<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);


// Database connection settings
$servername = "localhost";
$username = "root";
$password = "";
$dbname = "valentines";

$conn = new mysqli($servername, $username, $password, $dbname);

// Check connection
if ($conn->connect_error) {
    die("Connection failed: " . $conn->connect_error);
}


if ($_SERVER['REQUEST_METHOD'] == 'POST') {
    // Get form data
    $name = $_POST['name'];
    $email = $_POST['email'];
    $password = $_POST['password'];
    $confirm_password = $_POST['confirm-password'];

    // Check if the passwords match
    if ($password !== $confirm_password) {
        echo "Passwords do not match!";
        exit();
    }

    // Hash the password
    $hashed_password = password_hash($password, PASSWORD_BCRYPT);  // Hash the password after comparison

    // Generate a unique code (8 characters)
    $code = strtoupper(bin2hex(random_bytes(4)));  // Original autogenerated code

    // Generate a unique reference number (8 characters)
    $reference_number = strtoupper(bin2hex(random_bytes(4)));  // New unique 8-character reference number

    // Insert data into the database
    $stmt = $conn->prepare("INSERT INTO users (name, email, password, code, reference_number) VALUES (?, ?, ?, ?, ?)");
    $stmt->bind_param("sssss", $name, $email, $hashed_password, $code, $reference_number);

    if ($stmt->execute()) {
        // Display success message in a prompt and redirect to login page
        echo "<script>
                alert('Account created successfully! Your reference number is: $reference_number');
                window.location.href = 'sign-in.php';
              </script>";
    } else {
        echo "<script>alert('Error: " . $stmt->error . "');</script>";
    }

    $stmt->close();
}

$conn->close();
?>



<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="style.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <style>
        /* Include your styles here */
    </style>
</head>
<body>
    <style>
    body {
    margin: 0;
    font-family: 'Arial', sans-serif;
    background-color: #ffecf0;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    overflow: hidden;
    position: relative;
}

.container {
    text-align: center;
    background-color: #fff;
    background-image: url('bg.jpg');
    background-size: cover;
    background-position: center;
    padding: 20px;
    border-radius: 15px;
    box-shadow: 0 8px 16px rgba(228, 98, 98, 0.986);
    border: 5px dotted #ff99cc;
    position: relative;
    overflow: hidden;
    max-width: 400px;
    width: 100%;
    z-index: 1;
    height: 545px;
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}

h1, h2 {
    font-family: 'Dancing Script', cursive;
    font-size: 2rem;
    color: #ff6699;
    margin-bottom: 20px;
}

.button {
    padding: 10px 20px;
    font-size: 1rem;
    color: white;
    background: linear-gradient(to bottom right, #ff99cc, #ff6699);
    border: none;
    border-radius: 30px;
    cursor: pointer;
    position: relative;
    overflow: hidden;
    outline: none;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    margin-top: 20px; /* Added margin to separate the button from the text */
}

.button:hover {
    background: linear-gradient(to bottom right, #ff6699, #ff3366);
}

form {
    background-color: rgba(255, 255, 255, 0.9);
    padding: 30px;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    max-width: 350px;
    width: 100%;
    text-align: left;
    margin-top: 20px;
}

label {
    display: block;
    margin-bottom: 8px;
    font-weight: bold;
    color: #ff6699;
}

input {
    width: calc(100% - 20px);
    padding: 7px;
    margin-bottom: 15px;
    border: 2px solid #ff99cc;
    border-radius: 10px;
    background-color: #fff;
    box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);
}

input:focus {
    border-color: #ff6699;
    outline: none;
}

p {
    margin-top: 15px;
    color: #ff6699;
}

a {
    color: #ff3366;
    text-decoration: none;
    font-weight: bold;
}

a:hover {
    text-decoration: underline;
}

.heart {
    width: 20px;
    height: 20px;
    background-color: #ff6699;
    position: absolute;
    border-radius: 50% 50% 0 0;
    transform: rotate(-45deg);
    animation: float 5s infinite;
}

.heart::before,
.heart::after {
    content: '';
    width: 20px;
    height: 20px;
    background-color: #ff6699;
    position: absolute;
    border-radius: 50%;
}

.heart::before {
    top: -10px;
    left: 0;
}

.heart::after {
    top: 0;
    left: -10px;
}

@keyframes float {
    0% {
        transform: translateY(0) rotate(-45deg);
    }
    50% {
        transform: translateY(-20px) rotate(-45deg);
    }
    100% {
        transform: translateY(0) rotate(-45deg);
    }
}


@keyframes float {
    0% {
        transform: translateY(0) rotate(-45deg);
    }
    50% {
        transform: translateY(-20px) rotate(-45deg);
    }
    100% {
        transform: translateY(0) rotate(-45deg);
    }
}

@media (max-width: 480px) {
    body {
        margin: 0;
        font-family: 'Arial', sans-serif;
        background-color: #ffecf0;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
        overflow: hidden;
        position: relative;
    }
    
    .container {
        text-align: center;
        background-color: #fff;
        background-image: url('bg.jpg');
        background-size: cover;
        background-position: center;
        padding: -15px;
        border-radius: 15px;
        box-shadow: 0 8px 16px rgba(228, 98, 98, 0.986);
        border: 5px dotted #ff99cc;
        position: relative;
        overflow: hidden;
        max-width: 350px;  /* Reduced max-width */
        width: 100%;
        z-index: 1;
        height: 450px;  /* Reduced height */
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    
    
    h1, h2 {
        font-family: 'Dancing Script', cursive;
        font-size: 2rem;
        color: #ff6699;
        margin-bottom: 20px;
    }
    
    .button {
        padding: 10px 14px;
        font-size: 0.8rem;
        color: white;
        background: linear-gradient(to bottom right, #ff99cc, #ff6699);
        border: none;
        border-radius: 30px;
        cursor: pointer;
        position: relative;
        overflow: hidden;
        outline: none;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        margin-top: 2px; /* Added margin to separate the button from the text */
    }
    
    .button:hover {
        background: linear-gradient(to bottom right, #ff6699, #ff3366);
    }
    
    form {
        background-color: rgba(255, 255, 255, 0.9);
        padding: 10px;
        border-radius: 10px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
        max-width: 350px;
        width: 100%;
        text-align: left;
        margin-top: 20px;
    }
    
    label {
        display: block;
        margin-bottom: -2px;
        font-weight: bold;
        color: #ff6699;
    }
    
    input {
        width: calc(100% - 20px);
        padding: 7px;
        margin-bottom: 15px;
        border: 2px solid #ff99cc;
        border-radius: 10px;
        background-color: #fff;
        box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.1);
    }
    
    input:focus {
        border-color: #ff6699;
        outline: none;
    }
    
    p {
        margin-top: 15px;
        color: #ff6699;
    }
    
    a {
        color: #ff3366;
        text-decoration: none;
        font-weight: bold;
    }
    
    a:hover {
        text-decoration: underline;
    }
    
    .heart {
        width: 20px;
        height: 20px;
        background-color: #ff6699;
        position: absolute;
        border-radius: 50% 50% 0 0;
        transform: rotate(-45deg);
        animation: float 5s infinite;
    }
    
    .heart::before,
    .heart::after {
        content: '';
        width: 20px;
        height: 20px;
        background-color: #ff6699;
        position: absolute;
        border-radius: 50%;
    }
    
    .heart::before {
        top: -10px;
        left: 0;
    }
    
    .heart::after {
        top: 0;
        left: -10px;
    }

}
</style>
    <div class="background-hearts">
        <!-- Heart animations -->
    </div>
    <div class="container form-container signup show">
    <form action="signup.php" method="POST">
    <h2>Sign Up</h2>
    <label for="name">Name</label>
    <input type="text" id="name" name="name" required>
    <label for="email">Email</label>
    <input type="email" id="email" name="email" required>
    <label for="password">Password</label>
    <input type="password" id="password" name="password" required>
    <label for="confirm-password">Confirm Password</label>
    <input type="password" id="confirm-password" name="confirm-password" required>
    <button class="button" type="submit">Sign Up</button>
</form>
        <p>Already have an account? <a href="sign-in.php">Sign In</a></p>
    </div>
    <div class="background-hearts">
        <div class="heart" style="top: 10%; left: 20%; animation-delay: 0s;"></div>
        <div class="heart" style="top: 20%; left: 60%; animation-delay: 1s;"></div>
        <div class="heart" style="top: 30%; left: 40%; animation-delay: 2s;"></div>
        <div class="heart" style="top: 50%; left: 70%; animation-delay: 3s;"></div>
        <div class="heart" style="top: 60%; left: 30%; animation-delay: 4s;"></div>
        <div class="heart" style="top: 70%; left: 80%; animation-delay: 5s;"></div>
        <div class="heart" style="top: 80%; left: 50%; animation-delay: 6s;"></div>
        <div class="heart" style="top: 90%; left: 20%; animation-delay: 7s;"></div>
        
    </div>
</body>
</html>
